_common/date-time-format.txt
Includes comments of analysis of current content across projects.
=> Adds updated content for the Date time format topic

_common/authentication.txt
Made with parts of the Identity Quickstart guide, and the Cloud Files authentication section on developer.rackspace.com.
=> Created common content for authentication.txt

_common/glossary.txt, _common/request-response-json.txt, _common/request-response-xml.txt
added sample request and response for json
=> added sample code to json request/response

_common/how-curl-commands-work.txt, _common/service-access-endpoints-table.txt, _common/service-access.txt
Cleaned up and reorged a  bit.  I'm not sure this section really belongs in dev guides.  May fit better in Getting Started Guides.  Here it is anyway!  -- Cat
=> How cURL commands work  (Reviewer: pending comments for Cat Lookabaugh)

_common/glossary.txt
Added lines for Cloud Block Storage definition.
=> Updated volume definition

.gitignore, rst/getting-started-content-architecture/readme.md
Added some notes to the bottom of the readme about updating `conf.py` exclude_patterns and rst_epilog sections.
=> adding notes about conf.py updates to readme

common-gs/auth-using-curl.rst, common-gs/get-credentials.rst, common-gs/how-to-use-curl.rst, common-gs/samples/auth-req-curl.rst, requirements.txt
=> Apply Editor changes to common GS authentication topics

templates/getting-started/common-gs/auth-using-curl.rst
Just one or two small edits. No rush.
=> Small edit to common file

templates/getting-started/getting-started.rst
I revised the topic to reflect the latest changes that were made based on the TOC revisions. I suppose there is a chance it might need further revision, based on feedback, but I wanted to get it started. (ha) I am not sure about the toctree, nor the comment I inserted. Revise as necessary.
👍
=> Revise getting started topic with latest changes

api-guide-template/common-gs/how-to-use-curl.rst
=> remove extra :ref:

templates/getting-started/common-gs/how-to-use-curl.rst, templates/getting-started/getting-started/send-request-ovw.rst
Some broken links were reported (see https://github.com/rackerlabs/docs-common/issues/58). This PR fixes them.
=> Updated broken links in common topics

api-guide-template/copyright.rst
- Wrap lines to 79 characters
- Fix header separator
=> Fix RST syntax

api-guide-template/conf.py
conf.py:  
'rax-cart': ('http://cart.rackspace.com/%s', ''),
'rax-special': ('http://%s.rackspace.com/', ''),
More PRs will follow to take advantage of this addition.
=> Added some handy extlinks

api-guide-template/additional-resources.rst
=> Took advantage of rax-special extlink

api-guide-template/getting-started/index.rst
=> Took advantage of rax-cart extlink

api-guide-template/common-gs/samples/auth-req-curl.rst, api-guide-template/conf.py, api-guide-template/general-api-info/service-access.rst, api-guide-template/getting-started/install-CLI-client.rst, api-guide-template/service-updates.rst
- Fix pep8 errors in conf.py
- Add import statements back
- Add Service updates topic
- Fix formatting on auth req example
=> Template updates

api-guide-template/general-api-info/api-behavior.rst, api-guide-template/general-api-info/compatible-shared-load-balancing-protocols.rst, api-guide-template/general-api-info/date-time-format.rst, api-guide-template/general-api-info/faults.rst, api-guide-template/general-api-info/limits.rst, api-guide-template/general-api-info/paginated-collections.rst, api-guide-template/general-api-info/request-response.rst, api-guide-template/general-api-info/role-based-access-control.rst, api-guide-template/general-api-info/service-access.rst, api-guide-template/getting-started/send-request-ovw.rst
- Update SDK and CLI links in ``send-request-ovw`` to use extlink ref
- Remove book prefixes from refills
- Replaced some product-specific reference with substitution variable.
=> Template updates and corrections

api-guide-template/general-api-info/role-based-access-control.rst
Use |product name| substitution variable in template
=> Replace load balancers with variable

api-guide-template/common-gs/auth-using-curl.rst
- Changed extlink to :rax-dev:
- Update link to use permalink to the Authentication token headline
=> Fix broken link

api-guide-template/common-gs/auth-using-curl.rst, api-guide-template/general-api-info/http-status-codes.rst, api-guide-template/general-api-info/index.rst, api-guide-template/general-api-info/role-based-access-control.rst, api-guide-template/getting-started/authenticate.rst
- Update common auth links for refactored content
- Add HTTP status code topics to replace faults.rst
=> Fix links and add status codes
